version: '3.9'
name: tp1
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    networks:
      - testing_net
    ports:
      - "15672:15672"

  reducer-ex1-1:
    container_name: dim_reducer_reducer-ex1-1
    image: dim_reducer:latest
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - CLI_RABBITMQ_QUEUE_INPUT=dim_reducer_saver_1
      - CLI_RABBITMQ_QUEUE_OUTPUT=saver1_queue
      - CLI_REDUCER_COLUMNS=legId,route,totalFare
    networks:
      - testing_net
    volumes:
      - ./dim_reducer/config.yaml:/config.yaml
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 15
        window: 10s

  reducer-ex2-1:
    container_name: dim_reducer_reducer-ex2-1
    image: dim_reducer:latest
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - CLI_RABBITMQ_QUEUE_INPUT=dim_reducer_saver_2
      - CLI_RABBITMQ_QUEUE_OUTPUT=saver2_queue
      - CLI_REDUCER_COLUMNS=legId,route
    networks:
      - testing_net
    volumes:
      - ./dim_reducer/config.yaml:/config.yaml
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 15
        window: 10s

  filter_stopovers-1:
    container_name: filter_stopovers-1
    image: filter_escalas:latest
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - CLI_RABBITMQ_QUEUES_INPUT=filters_stopovers
      - CLI_RABBITMQ_QUEUES_OUTPUT=saver_3,dim_reducer_saver_1
    networks:
      - testing_net
    volumes:
      - ./filters/filter_escalas/config.yaml:/config.yaml
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 15
        window: 10s

  data_processor-1:
    container_name: data_processor-1
    image: data_processor:latest
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - CLI_RABBITMQ_QUEUE_INPUT=flight_row_processor
      - CLI_RABBITMQ_QUEUE_OUTPUT_EX123=filters_stopovers,distance_calculator
      - CLI_RABBITMQ_QUEUE_OUTPUT_EX4=ex4_solver
    networks:
      - testing_net
    volumes:
      - ./data_processor/config.yaml:/config.yaml
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 15
        window: 10s

  filter_distances-1:
    container_name: filter_distances-1
    image: filter_distancias:latest
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - CLI_RABBITMQ_QUEUES_INPUT=filters_distances
      - CLI_RABBITMQ_QUEUES_OUTPUT=dim_reducer_saver_2
    networks:
      - testing_net
    volumes:
      - ./filters/filter_distancias/config.yaml:/config.yaml
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 15
        window: 10s

  distance_completer-1:
    container_name: distance_completer-1
    image: distance_completer:latest
    environment:
      - CLI_ID=6
      - CLI_LOG_LEVEL=DEBUG
      - CLI_RABBITMQ_QUEUE_INPUT_FLIGHTS=distance_calculator
      - CLI_RABBITMQ_QUEUE_INPUT_AIRPORT=airports_saver
      - CLI_RABBITMQ_QUEUES_OUTPUT=filters_distances
      - CLI_RABBITMQ_QUEUE_INPUT_AIRPORTEXCHANGE=AirportsExchange
      - CLI_RABBITMQ_QUEUE_INPUT_AIRPORTROUTINGKEY=airports
      - CLI_COMPLETER_FILENAME=airports.csv
    networks:
      - testing_net
    volumes:
      - ./distance_completer/config.yaml:/config.yaml
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 15
        window: 10s

  saver-ex1:
    container_name: saver-ex1
    image: simple_saver:latest
    environment:
      - CLI_ID=7
      - CLI_LOG_LEVEL=DEBUG
      - CLI_RABBITMQ_QUEUE_INPUT=dim_reducer_saver_1
      - CLI_SAVER_OUTPUT=results_ex1.csv
    networks:
      - testing_net
    volumes:
      - ./simple_saver/config.yaml:/config.yaml
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 15
        window: 10s

  saver-ex2:
    container_name: saver-ex2
    image: simple_saver:latest
    environment:
      - CLI_ID=8
      - CLI_LOG_LEVEL=DEBUG
      - CLI_RABBITMQ_QUEUE_INPUT=dim_reducer_saver_2
      - CLI_SAVER_OUTPUT=results_ex2.csv
    networks:
      - testing_net
    volumes:
      - ./simple_saver/config.yaml:/config.yaml
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 15
        window: 10s

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24