{# templates/docker-compose-clients.yaml #}
version: '3.9'
name: tp1
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    networks:
      - testing_net
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

{% for i in range(1,reducers1 + 1) %}
  reducer-ex1-{{i}}:
    container_name: dim_reducer_reducer-ex1-{{i}}
    image: dim_reducer:latest
    environment:
      - CLI_ID={{i}}
      - CLI_NAME=dim_reducer_reducer-ex1-{{i}}
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUE_INPUT=dim_reducer_saver_1
      - CLI_RABBITMQ_QUEUE_OUTPUT=saver1_queue
      - CLI_REDUCER_COLUMNS=legId,route,totalFare
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./dim_reducer/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy
{% endfor %}

{% for i in range(1,reducers2 + 1) %}
  reducer-ex2-{{i}}:
    container_name: dim_reducer_reducer-ex2-{{i}}
    image: dim_reducer:latest
    environment:
      - CLI_ID={{reducers1 + i}}
      - CLI_NAME=dim_reducer_reducer-ex2-{{i}}
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUE_INPUT=dim_reducer_saver_2
      - CLI_RABBITMQ_QUEUE_OUTPUT=saver2_queue
      - CLI_REDUCER_COLUMNS=legId,route
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./dim_reducer/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy
{% endfor %}


{% for i in range(1,stopovers + 1) %}
  filter_stopovers-{{i}}:
    container_name: filter_stopovers-{{i}}
    image: filter_escalas:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + i}}
      - CLI_NAME=filter_stopovers-{{i}}
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUES_INPUT=filters_stopovers
      - CLI_RABBITMQ_QUEUES_OUTPUT=saver_3,dim_reducer_saver_1
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./filters/filter_escalas/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy
{% endfor %}

{% for i in range(1,processors + 1) %}
  data_processor-{{i}}:
    container_name: data_processor-{{i}}
    image: data_processor:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + i}}
      - CLI_NAME=data_processor-{{i}}
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUE_INPUT=flight_row_processor
      - CLI_RABBITMQ_QUEUE_OUTPUT_EX123=filters_stopovers,distance_calculator
      - CLI_RABBITMQ_QUEUE_OUTPUT_EX4=ex4_solver
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./data_processor/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy
{% endfor %}

{% for i in range(1,distances + 1) %}
  filter_distances-{{i}}:
    container_name: filter_distances-{{i}}
    image: filter_distancias:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + i}}
      - CLI_NAME=filter_distances-{{i}}
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUES_INPUT=filters_distances
      - CLI_RABBITMQ_QUEUES_OUTPUT=dim_reducer_saver_2
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./filters/filter_distancias/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy
{% endfor %}

{% for i in range(1,completers + 1) %}
  distance_completer-{{i}}:
    container_name: distance_completer-{{i}}
    image: distance_completer:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + i}}
      - CLI_NAME=distance_completer-{{i}}
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUE_INPUT_FLIGHTS=distance_calculator
      - CLI_RABBITMQ_QUEUE_INPUT_AIRPORT=airports_saver
      - CLI_RABBITMQ_QUEUES_OUTPUT=filters_distances
      - CLI_QUEUES_AIRPORTS_EXCHANGE_TYPE=fanout
      - CLI_RABBITMQ_QUEUE_INPUT_AIRPORTEXCHANGE=AirportsExchange
      - CLI_RABBITMQ_QUEUE_INPUT_AIRPORTROUTINGKEY=airports
      - CLI_COMPLETER_FILENAME=flightrows.csv
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./distance_completer/config.yaml:/config.yaml
    depends_on:
        rabbitmq:
          condition: service_healthy
{% endfor %}

{% for i in range(1,ex4Savers + 1) %}
  ex4_journey_saver-{{i}}:
    container_name: ex4_saver-{{i}}
    image: ex4_journey_saver:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + completers + i}}
      - CLI_NAME=ex4_saver-{{i}}
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUE_INPUT=journey_savers_ex4_queue
      - CLI_RABBITMQ_QUEUE_OUTPUTS_ACCUM=accum_ex4_queue
      - CLI_RABBITMQ_QUEUE_OUTPUTS_SAVER=sink_ex4_queue
      - CLI_INTERNAL_SAVERS_COUNT=6
      - CLI_RABBITMQ_RK_INPUT={{6*(i-1)}}
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./ex4_journey_saver/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy
{% endfor %}

{% for i in range(1,ex4Dispatchers + 1) %}
  ex4_dispatcher-{{i}}:
    container_name: ex4_dispatcher-{{i}}
    image: dispatcher_ex4:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + completers + ex4Savers + i}}
      - CLI_NAME=ex4_dispatcher-{{i}}
      - CLI_LOG_LEVEL=DEBUG
      - CLI_RABBITMQ_QUEUE_INPUT=ex4_solver
      - CLI_RABBITMQ_QUEUE_OUTPUT=journey_savers_ex4_queue
      - CLI_SAVERS_COUNT={{6*ex4Savers}}
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./dispatcher_ex4/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy
{% for j in range(1,ex4Savers + 1) %}
      ex4_journey_saver-{{j}}:
        condition: service_started
{% endfor %}
{% endfor %}

  avg_calculator_ex4:
    container_name: avg_calculator_ex4
    image: avg_calculator_ex4:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + completers + ex4Savers + ex4Dispatchers + 1}}
      - CLI_NAME=avg_calculator_ex4
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUE_INPUT=accum_ex4_queue
      - CLI_RABBITMQ_QUEUE_OUTPUT=journey_savers_ex4_queue
      - CLI_SAVERS_COUNT={{6*ex4Savers}}
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./avg_calculator_ex4/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy

  ex4_sink:
    container_name: ex4_sink
    image: ex4_sink:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + completers + ex4Savers + ex4Dispatchers + 2}}
      - CLI_NAME=ex4_sink
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUE_INPUT=sink_ex4_queue
      - CLI_RABBITMQ_QUEUE_OUTPUT=saver4_queue
      - CLI_SAVERS_COUNT={{6*ex4Savers}}
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./ex4_sink/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy


  saver-ex1:
    container_name: saver-ex1
    image: simple_saver:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + completers + ex4Savers + ex4Dispatchers + 3}}
      - CLI_NAME=saver-ex1
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUE_INPUT=saver1_queue
      - CLI_SAVER_OUTPUT=results_ex1.csv
      - CLI_GETTER_BATCH_LINES=100
      - CLI_GETTER_ADDRESS=saver-ex1:8080
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./simple_saver/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy

  saver-ex2:
    container_name: saver-ex2
    image: simple_saver:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + completers + ex4Savers + ex4Dispatchers  + 4}}
      - CLI_NAME=saver-ex2
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUE_INPUT=saver2_queue
      - CLI_SAVER_OUTPUT=results_ex2.csv
      - CLI_GETTER_BATCH_LINES=100
      - CLI_GETTER_ADDRESS=saver-ex2:8080
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./simple_saver/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy

  saver-ex3:
    container_name: saver-ex3
    image: saver_ex_3:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + completers + ex4Savers + ex4Dispatchers  + 5}}
      - CLI_NAME=saver-ex3
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUE_INPUT=saver_3
      - CLI_SAVER_OUTPUT=results_ex3
      - CLI_GETTER_BATCH_LINES=100
      - CLI_GETTER_ADDRESS=saver-ex3:8080
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./saver_ex_3/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy

  saver-ex4:
    container_name: saver-ex4
    image: simple_saver:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + completers + ex4Savers + ex4Dispatchers  + 6}}
      - CLI_NAME=saver-ex4
      - CLI_LOG_LEVEL=INFO
      - CLI_RABBITMQ_QUEUE_INPUT=saver4_queue
      - CLI_SAVER_OUTPUT=results_ex4.csv
      - CLI_GETTER_BATCH_LINES=100
      - CLI_GETTER_ADDRESS=saver-ex4:8080
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./simple_saver/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy

  server:
    container_name: server
    image: server:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + completers + ex4Savers + ex4Dispatchers  + 7}}
      - CLI_NAME=server
      - CLI_LOG_LEVEL=INFO
      - CLI_GETTER_ADDRESSES=saver-ex1:8080,saver-ex2:8080,saver-ex3:8080,saver-ex4:8080
      - CLI_QUEUES_AIRPORTS_EXCHANGE_TYPE=fanout
      - CLI_QUEUES_AIRPORTS_EXCHANGE_NAME=AirportsExchange
      - CLI_QUEUES_AIRPORTS_EXCHANGE_ROUTINGKEY=airports
      - CLI_QUEUES_FLIGHTROWS=flight_row_processor
      - CLI_HEALTHCHECKER_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}healthchecker-{{hc}}:8080{{ "," if not loop.last else "" }}{% endfor %}
    networks:
      - testing_net
    volumes:
      - ./server/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy
      saver-ex1:
        condition: service_started
      saver-ex2:
        condition: service_started
      saver-ex3:
        condition: service_started
      saver-ex4:
        condition: service_started
      distance_completer-1:
        condition: service_started

  client:
    container_name: client
    image: client:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + completers + ex4Savers + ex4Dispatchers + 8}}
      - CLI_LOG_LEVEL=INFO
      - CLI_INPUT_BATCH=100
      - CLI_INPUT_AIRPORTS=/data/airports.csv # configurar localmente
      - CLI_INPUT_FILE=/data/flightrows.csv # configurar localmente
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./data:/data
    depends_on:
      server:
        condition: service_started

{% for i in range (1, healthcheckers+1) %}
  healthchecker-{{i}}:
    container_name: healthchecker-{{i}}
    image: healthchecker:latest
    environment:
      - CLI_ID={{reducers1 + reducers2 + stopovers + processors + distances + completers + ex4Savers + ex4Dispatchers + 8 + i}}
      - CLI_LOG_LEVEL=DEBUG
      - CLI_NAME=healthchecker-{{i}}
      - CLI_HEALTHCHECKER_ADDRESS=healthchecker-{{i}}:8080
      - CLI_HEALTHCHECKER_ID_ADDRESSES = {% for hc in range(1,healthcheckers + 1) %}{{ hc|string+":healthchecker-"+hc|string+":8081" if not hc==i else "" }}{{ "," if not loop.last and not hc == i and not(i == healthcheckers and hc == (i-1)) else "" }}{% endfor %}
      - CLI_HEALTHCHECKER_UDP_ADDRESS = healthchecker-{{i}}:8081
      - CLI_HEALTHCHECKER_ELECTION_ID = {{i}}
    networks:
      - testing_net
    volumes:
      - ./healthchecker/config.yaml:/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
{% endfor %}

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
