package utils

const CommaSeparator = ","
const DotCommaSeparator = ";"

const AirportCode = "Airport Code"
const Latitude = "Latitude"
const Longitude = "Longitude"

const LegId = "legId"
const StartingAirport = "startingAirport"
const DestinationAirport = "destinationAirport"
const TravelDuration = "travelDuration"
const TotalFare = "totalFare"
const TotalTravelDistance = "totalTravelDistance"
const DirectDistance = "directDistance"
const TotalStopovers = "totalStopovers"
const SegmentsArrivalAirportCode = "segmentsArrivalAirportCode"
const SegmentsAirlineName = "segmentsAirlineName"
const LocalPrice = "localPrice"
const LocalQuantity = "localQuantity"
const Avg = "avg"
const Max = "max"
const PrevSent = "prevSent"
const LocalReceived = "localReceived"
const LocalSent = "localSent"
