# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        go build -v ./common/...
        go build -v -o dim_reducer_service.exe ./dim_reducer/...
        go build -v -o data_processor_service.exe ./data_processor/...
        go build -v -o filter_escalas.exe ./filters/filter_escalas/...

    - name: Test
      run: |
        go test -v ./common/...
        go test -v ./dim_reducer/... 
        go test -v ./data_processor/... 
        go test -v ./filters/filter_escalas/... 
